version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql

  postgresql:
    image: postgres
    container_name: postgresql-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    environment:
      NEO4J_AUTH: neo4j/Akashjais@929
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt protocol (used by Spring Boot)
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import

  adminer:
    image: adminer:latest
    container_name: adminer-container
    restart: always
    ports:
      - "3000:8080"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # Messaging
    environment:
      RABBITMQ_DEFAULT_USER: culeAkash
      RABBITMQ_DEFAULT_PASS: Akashjais@929
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: culeAkash
      MINIO_ROOT_PASSWORD: Akashjais@929
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  mysql_data:
  rabbitmq_data:
  minio_data:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import: